FROM maven:3.9.5 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the project files
COPY . .

# Define a build argument for the Spring profile
ARG SPRING_PROFILE

RUN mvn clean install -DskipTests


# Expose the port that your Spring Boot application will run on
EXPOSE 8080

# Define the command to run your application
CMD ["java", "-jar", "/app/target/xxxxxx-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=${SPRING_PROFILE}"]
