# Use the official Node.js 18 image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package*.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the application code
COPY . .

# run build command
# RUN npm build:env

# Expose the port
EXPOSE 3000

# Run the command to start the development server
CMD ["npm", "run", "start:env"]

